spring:
datasource:
url: jdbc:postgresql://localhost:5432/financedb
username: postgres
password: sua_senha
jpa:
hibernate:
ddl-auto: update
show-sql: true
properties:
hibernate:
format_sql: true

server:
port: 8080

jwt:
secret: sua-chave-secreta-bem-longa-aqui-com-pelo-menos-256-bits
expiration: 86400000